/**
 * build-env.js — Vercel Pre-Build Script
 * =========================================
 * Reads the RENDER_API_URL environment variable (set in Vercel dashboard)
 * and writes env-config.js so the frontend knows the Render backend URL.
 *
 * Run automatically by Vercel before serving static files.
 */

const fs = require('fs');
const path = require('path');

const renderApiUrl = (process.env.RENDER_API_URL || '').replace(/\/$/, '');

if (!renderApiUrl) {
    console.warn('[build-env] ⚠️  RENDER_API_URL not set — frontend will use LAN auto-discovery.');
    console.warn('[build-env]    Set RENDER_API_URL in Vercel → Settings → Environment Variables');
}

const content = `/* Auto-generated by build-env.js — DO NOT edit manually */
/* Re-generated on each Vercel deployment */
(function() {
    var renderUrl = ${JSON.stringify(renderApiUrl)};
    if (renderUrl) {
        window.KISAAN_RENDER_URL = renderUrl;
        window.KISAAN_API_URL    = renderUrl + '/api';
        console.log('[KisaanEnv] 🌐 Production API:', window.KISAAN_API_URL);
    } else {
        console.warn('[KisaanEnv] ⚠️ RENDER_API_URL not configured — using auto-discovery');
    }
})();
`;

const outPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[build-env] ✅ env-config.js written →', renderApiUrl || '(empty — LAN mode)');
