/**
 * build-env.js — Vercel/GitHub Pages Pre-Build Script
 * ==================================================
 * Reads the RENDER_API_URL environment variable
 * and writes env-config.js so the frontend knows the Render backend URL.
 * 
 * Also packages a clean 'dist' folder with only static frontend assets.
 */

const fs = require('fs');
const path = require('path');

const renderApiUrl = (process.env.RENDER_API_URL || '').replace(/\/$/, '');

if (!renderApiUrl) {
    console.warn('[build-env] ⚠️  RENDER_API_URL not set — frontend will use LAN auto-discovery.');
    console.warn('[build-env]    Set RENDER_API_URL in Vercel → Settings → Environment Variables');
}

const content = `/* Auto-generated by build-env.js — DO NOT edit manually */
/* Re-generated on each deployment */
(function() {
    var renderUrl = ${JSON.stringify(renderApiUrl)};
    if (renderUrl) {
        window.KISAAN_RENDER_URL = renderUrl;
        window.KISAAN_API_URL    = renderUrl + '/api';
        console.log('[KisaanEnv] 🌐 Production API:', window.KISAAN_API_URL);
    } else {
        console.warn('[KisaanEnv] ⚠️ RENDER_API_URL not configured — using auto-discovery');
    }
})();
`;

// 1. Write to root directory (for local testing/fallback)
const rootOutPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(rootOutPath, content, 'utf8');
console.log('[build-env] ✅ env-config.js written to root →', renderApiUrl || '(empty — LAN mode)');

// 2. Build a clean 'dist' folder for deployment
const distPath = path.join(__dirname, 'dist');
if (!fs.existsSync(distPath)) {
    fs.mkdirSync(distPath, { recursive: true });
}

// Write env-config.js to dist
fs.writeFileSync(path.join(distPath, 'env-config.js'), content, 'utf8');

// List of frontend files to copy to dist
const filesToCopy = [
    'index.html',
    'farmer-dashboard.html',
    'customer-dashboard.html',
    'admin-dashboard.html',
    'admin-login.html',
    'landing.html',
    'offline.html',
    'sw.js',
    'kisaan-network.js',
    'logo.png',
    'farmer-mascot.png',
    'farmer-mascot.svg',
    'fruits.png',
    'veggies.png',
    'manifest.json',
    'temp.css',
    'test-report.html',
];

// Copy each file
let copiedCount = 0;
filesToCopy.forEach(file => {
    const src = path.join(__dirname, file);
    const dest = path.join(distPath, file);
    if (fs.existsSync(src)) {
        fs.copyFileSync(src, dest);
        copiedCount++;
    }
});

console.log(`[build-env] ✅ Clean dist/ folder generated with ${copiedCount} files for web deployment.`);
