/* Auto-generated by build-env.js — DO NOT edit manually */
/* Re-generated on each Vercel deployment */
(function() {
    var renderUrl = "";
    if (renderUrl) {
        window.KISAAN_RENDER_URL = renderUrl;
        window.KISAAN_API_URL    = renderUrl + '/api';
        console.log('[KisaanEnv] 🌐 Production API:', window.KISAAN_API_URL);
    } else {
        console.warn('[KisaanEnv] ⚠️ RENDER_API_URL not configured — using auto-discovery');
    }
})();
