/* env-config.js — KisaanConnect Frontend Environment Config
 * ============================================================
 * This file is AUTO-GENERATED by build-env.js during Vercel deployment.
 * It will be overwritten on every deploy with the correct Render API URL.
 *
 * For LOCAL development: leave this file as-is.
 * For PRODUCTION: set RENDER_API_URL in Vercel → Settings → Environment Variables.
 */
(function() {
    var renderUrl = "";
    if (renderUrl) {
        window.KISAAN_RENDER_URL = renderUrl;
        window.KISAAN_API_URL    = renderUrl + '/api';
        console.log('[KisaanEnv] 🌐 Production API:', window.KISAAN_API_URL);
    } else {
        console.warn('[KisaanEnv] ℹ️  Running in LAN/local mode — kisaan-network.js will auto-discover server');
    }
})();
